<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Nationality;

class NationalitySeeder extends Seeder
{
    private $nationality;

    public function __construct(Nationality $nationality)
    {
        $this->nationality = $nationality;
    }

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $nationalities = [
            ['name' => 'Iceland', 'description' => 'アイスランド共和国', 'countrycode' => 'IS'],
            ['name' => 'Ireland', 'description' => 'アイルランド', 'countrycode' => 'IE'],
            ['name' => 'Azerbaijan', 'description' => 'アゼルバイジャン共和国', 'countrycode' => 'AZ'],
            ['name' => 'Afghanistan', 'description' => 'アフガニスタン', 'countrycode' => 'AF'],
            ['name' => 'United States of America', 'description' => 'アメリカ合衆国', 'countrycode' => 'US'],
            ['name' => 'United Arab Emirates', 'description' => 'アラブ首長国連邦', 'countrycode' => 'AE'],
            ['name' => 'Algeria', 'description' => 'アルジェリア民主人民共和国', 'countrycode' => 'DZ'],
            ['name' => 'Argentina', 'description' => 'アルゼンチン共和国', 'countrycode' => 'AR'],
            ['name' => 'Albania', 'description' => 'アルバニア共和国', 'countrycode' => 'AL'],
            ['name' => 'Armenia', 'description' => 'アルメニア共和国', 'countrycode' => 'AM'],
            ['name' => 'Angola', 'description' => 'アンゴラ共和国', 'countrycode' => 'AO'],
            ['name' => 'Antigua and Barbuda', 'description' => 'アンティグア・バーブーダ', 'countrycode' => 'AG'],
            ['name' => 'Andorra', 'description' => 'アンドラ', 'countrycode' => 'AD'],
            ['name' => 'Yemen', 'description' => 'イエメン共和国', 'countrycode' => 'YE'],
            ['name' => 'Israel', 'description' => 'イスラエル国', 'countrycode' => 'IL'],
            ['name' => 'Italy', 'description' => 'イタリア共和国', 'countrycode' => 'IT'],
            ['name' => 'Iraq', 'description' => 'イラク共和国', 'countrycode' => 'IQ'],
            ['name' => 'Iran', 'description' => 'イラン・イスラム共和国', 'countrycode' => 'IR'],
            ['name' => 'India', 'description' => 'インド', 'countrycode' => 'IN'],
            ['name' => 'Indonesia', 'description' => 'インドネシア共和国', 'countrycode' => 'ID'],
            ['name' => 'Uganda', 'description' => 'ウガンダ共和国', 'countrycode' => 'UG'],
            ['name' => 'Ukraine', 'description' => 'ウクライナ', 'countrycode' => 'UA'],
            ['name' => 'Uzbekistan', 'description' => 'ウズベキスタン共和国', 'countrycode' => 'UZ'],
            ['name' => 'Uruguay', 'description' => 'ウルグアイ東方共和国', 'countrycode' => 'UY'],
            ['name' => 'Ecuador', 'description' => 'エクアドル共和国', 'countrycode' => 'EC'],
            ['name' => 'Egypt', 'description' => 'エジプト・アラブ共和国', 'countrycode' => 'EG'],
            ['name' => 'Estonia', 'description' => 'エストニア共和国', 'countrycode' => 'EE'],
            ['name' => 'Eswatini', 'description' => 'エスワティニ王国', 'countrycode' => 'SZ'],
            ['name' => 'Ethiopia', 'description' => 'エチオピア連邦民主共和国', 'countrycode' => 'ET'],
            ['name' => 'Eritrea', 'description' => 'エリトリア国', 'countrycode' => 'ER'],
            ['name' => 'El Salvador', 'description' => 'エルサルバドル共和国', 'countrycode' => 'SV'],
            ['name' => 'Australia', 'description' => 'オーストラリア連邦', 'countrycode' => 'AU'],
            ['name' => 'Austria', 'description' => 'オーストリア共和国', 'countrycode' => 'AT'],
            ['name' => 'Oman', 'description' => 'オマーン国', 'countrycode' => 'OM'],
            ['name' => 'Netherlands', 'description' => 'オランダ王国', 'countrycode' => 'NL'],
            ['name' => 'Ghana', 'description' => 'ガーナ共和国', 'countrycode' => 'GH'],
            ['name' => 'Cabo Verde', 'description' => 'カーボヴェルデ共和国', 'countrycode' => 'CV'],
            ['name' => 'Guyana', 'description' => 'ガイアナ共和国', 'countrycode' => 'GY'],
            ['name' => 'Kazakhstan', 'description' => 'カザフスタン共和国', 'countrycode' => 'KZ'],
            ['name' => 'Qatar', 'description' => 'カタール国', 'countrycode' => 'QA'],
            ['name' => 'Canada', 'description' => 'カナダ', 'countrycode' => 'CA'],
            ['name' => 'Gabon', 'description' => 'ガボン共和国', 'countrycode' => 'GA'],
            ['name' => 'Cameroon', 'description' => 'カメルーン共和国', 'countrycode' => 'CM'],
            ['name' => 'Gambia', 'description' => 'ガンビア共和国', 'countrycode' => 'GM'],
            ['name' => 'Cambodia', 'description' => 'カンボジア王国', 'countrycode' => 'KH'],
            ['name' => 'Republic of North Macedonia', 'description' => '北マケドニア共和国', 'countrycode' => 'MK'],
            ['name' => 'Guinea-Bissau', 'description' => 'ギニアビサウ共和国', 'countrycode' => 'GW'],
            ['name' => 'Guinea', 'description' => 'ギニア共和国', 'countrycode' => 'GN'],
            ['name' => 'Cyprus', 'description' => 'キプロス共和国', 'countrycode' => 'CY'],
            ['name' => 'Cuba', 'description' => 'キューバ共和国', 'countrycode' => 'CU'],
            ['name' => 'Greece', 'description' => 'ギリシャ共和国', 'countrycode' => 'GR'],
            ['name' => 'Kiribati', 'description' => 'キリバス共和国', 'countrycode' => 'KI'],
            ['name' => 'Kyrgyzstan', 'description' => 'キルギス共和国', 'countrycode' => 'KG'],
            ['name' => 'Cabo Verde', 'description' => 'カーボヴェルデ共和国', 'countrycode' => 'CV'],
            ['name' => 'Guyana', 'description' => 'ガイアナ共和国', 'countrycode' => 'GY'],
            ['name' => 'Kazakhstan', 'description' => 'カザフスタン共和国', 'countrycode' => 'KZ'],
            ['name' => 'Qatar', 'description' => 'カタール国', 'countrycode' => 'QA'],
            ['name' => 'Canada', 'description' => 'カナダ', 'countrycode' => 'CA'],
            ['name' => 'Gabon', 'description' => 'ガボン共和国', 'countrycode' => 'GA'],
            ['name' => 'Cameroon', 'description' => 'カメルーン共和国', 'countrycode' => 'CM'],
            ['name' => 'Gambia', 'description' => 'ガンビア共和国', 'countrycode' => 'GM'],
            ['name' => 'Cambodia', 'description' => 'カンボジア王国', 'countrycode' => 'KH'],
            ['name' => 'Republic of North Macedonia', 'description' => '北マケドニア共和国', 'countrycode' => 'MK'],
            ['name' => 'Guinea-Bissau', 'description' => 'ギニアビサウ共和国', 'countrycode' => 'GW'],
            ['name' => 'Guinea', 'description' => 'ギニア共和国', 'countrycode' => 'GN'],
            ['name' => 'Cyprus', 'description' => 'キプロス共和国', 'countrycode' => 'CY'],
            ['name' => 'Cuba', 'description' => 'キューバ共和国', 'countrycode' => 'CU'],
            ['name' => 'Greece', 'description' => 'ギリシャ共和国', 'countrycode' => 'GR'],
            ['name' => 'Kiribati', 'description' => 'キリバス共和国', 'countrycode' => 'KI'],
            ['name' => 'Kyrgyzstan', 'description' => 'キルギス共和国', 'countrycode' => 'KG'],
            ['name' => 'Guatemala', 'description' => 'グアテマラ共和国', 'countrycode' => 'GT'],
            ['name' => 'Kuwait', 'description' => 'クウェート国', 'countrycode' => 'KW'],
            ['name' => 'Cook Islands', 'description' => 'クック諸島', 'countrycode' => 'CK'],
            ['name' => 'United Kingdom', 'description' => 'グレート・ブリテン及び北部アイルランド連合王国', 'countrycode' => 'GB'],
            ['name' => 'Grenada', 'description' => 'グレナダ', 'countrycode' => 'GD'],
            ['name' => 'Croatia', 'description' => 'クロアチア共和国', 'countrycode' => 'HR'],
            ['name' => 'Kenya', 'description' => 'ケニア共和国', 'countrycode' => 'KE'],
            ['name' => 'Cote d\'Ivoire', 'description' => 'コートジボワール共和国', 'countrycode' => 'CI'],
            ['name' => 'Costa Rica', 'description' => 'コスタリカ共和国', 'countrycode' => 'CR'],
            ['name' => 'Comoros', 'description' => 'コモロ連合', 'countrycode' => 'KM'],
            ['name' => 'Colombia', 'description' => 'コロンビア共和国', 'countrycode' => 'CO'],
            ['name' => 'Congo', 'description' => 'コンゴ共和国', 'countrycode' => 'CG'],
            ['name' => 'Democratic Republic of Congo', 'description' => 'コンゴ民主共和国', 'countrycode' => 'CD'],
            ['name' => 'Saudi Arabia', 'description' => 'サウジアラビア王国', 'countrycode' => 'SA'],
            ['name' => 'Samoa', 'description' => 'サモア独立国', 'countrycode' => 'WS'],
            ['name' => 'Sao Tome and Principe', 'description' => 'サントメ・プリンシペ民主共和国', 'countrycode' => 'ST'],
            ['name' => 'Zambia', 'description' => 'ザンビア共和国', 'countrycode' => 'ZM'],
            ['name' => 'San Marino', 'description' => 'サンマリノ共和国', 'countrycode' => 'SM'],
            ['name' => 'Sierra Leone', 'description' => 'シエラレオネ共和国', 'countrycode' => 'SL'],
            ['name' => 'Djibouti', 'description' => 'ジブチ共和国', 'countrycode' => 'DJ'],
            ['name' => 'Jamaica', 'description' => 'ジャマイカ', 'countrycode' => 'JM'],
            ['name' => 'Georgia', 'description' => 'ジョージア', 'countrycode' => 'GE'],
            ['name' => 'Syrian Arab Republic', 'description' => 'シリア・アラブ共和国', 'countrycode' => 'SY'],
            ['name' => 'Singapore', 'description' => 'シンガポール共和国', 'countrycode' => 'SG'],
            ['name' => 'Zimbabwe', 'description' => 'ジンバブエ共和国', 'countrycode' => 'ZW'],
            ['name' => 'Switzerland', 'description' => 'スイス連邦', 'countrycode' => 'CH'],
            ['name' => 'Sweden', 'description' => 'スウェーデン王国', 'countrycode' => 'SE'],
            ['name' => 'Sudan', 'description' => 'スーダン共和国', 'countrycode' => 'SD'],
            ['name' => 'Spain', 'description' => 'スペイン', 'countrycode' => 'ES'],
            ['name' => 'Suriname', 'description' => 'スリナム共和国', 'countrycode' => 'SR'],
            ['name' => 'Sri Lanka', 'description' => 'スリランカ民主社会主義共和国', 'countrycode' => 'LK'],
            ['name' => 'Slovakia', 'description' => 'スロバキア共和国', 'countrycode' => 'SK'],
            ['name' => 'Slovenia', 'description' => 'スロベニア共和国', 'countrycode' => 'SI'],
            ['name' => 'Seychelles', 'description' => 'セーシェル共和国', 'countrycode' => 'SC'],
            ['name' => 'Equatorial Guinea', 'description' => '赤道ギニア共和国', 'countrycode' => 'GQ'],
            ['name' => 'Senegal', 'description' => 'セネガル共和国', 'countrycode' => 'SN'],
            ['name' => 'Republic of Serbia', 'description' => 'セルビア共和国', 'countrycode' => 'RS'],
            ['name' => 'Saint Kitts and Nevis', 'description' => 'セントクリストファー・ネーヴィス', 'countrycode' => 'KN'],
            ['name' => 'Saint Vincent and the Grenadines', 'description' => 'セントビンセントおよびグレナディーン 諸島', 'countrycode' => 'VC'],
            ['name' => 'Saint Lucia', 'description' => 'セントルシア', 'countrycode' => 'LC'],
            ['name' => 'Somalia', 'description' => 'ソマリア連邦共和国', 'countrycode' => 'SO'],
            ['name' => 'Solomon Islands', 'description' => 'ソロモン', 'countrycode' => 'SB'],
            ['name' => 'Thailand', 'description' => 'タイ王国', 'countrycode' => 'TH'],
            ['name' => 'Republic of Korea', 'description' => '大韓民国', 'countrycode' => 'KR'],
            ['name' => 'Tajikistan', 'description' => 'タジキスタン共和国', 'countrycode' => 'TJ'],
            ['name' => 'United Republic of Tanzania', 'description' => 'タンザニア連合共和国', 'countrycode' => 'TZ'],
            ['name' => 'Czechia', 'description' => 'チェコ共和国', 'countrycode' => 'CZ'],
            ['name' => 'Chad', 'description' => 'チャド共和国', 'countrycode' => 'TD'],
            ['name' => 'Central African Republic', 'description' => '中央アフリカ共和国', 'countrycode' => 'CF'],
            ['name' => 'China', 'description' => '中華人民共和国', 'countrycode' => 'CN'],
            ['name' => 'Tunisia', 'description' => 'チュニジア共和国', 'countrycode' => 'TN'],
            ['name' => 'Chile', 'description' => 'チリ共和国', 'countrycode' => 'CL'],
            ['name' => 'Tuvalu', 'description' => 'ツバル', 'countrycode' => 'TV'],
            ['name' => 'Denmark', 'description' => 'デンマーク王国', 'countrycode' => 'DK'],
            ['name' => 'Germany', 'description' => 'ドイツ連邦共和国', 'countrycode' => 'DE'],
            ['name' => 'Togo', 'description' => 'トーゴ共和国', 'countrycode' => 'TG'],
            ['name' => 'Dominican Republic', 'description' => 'ドミニカ共和国', 'countrycode' => 'DO'],
            ['name' => 'Dominica', 'description' => 'ドミニカ国', 'countrycode' => 'DM'],
            ['name' => 'Trinidad and Tobago', 'description' => 'トリニダード・トバゴ共和国', 'countrycode' => 'TT'],
            ['name' => 'Turkmenistan', 'description' => 'トルクメニスタン', 'countrycode' => 'TM'],
            ['name' => 'Turkey', 'description' => 'トルコ共和国', 'countrycode' => 'TR'],
            ['name' => 'Tonga', 'description' => 'トンガ王国', 'countrycode' => 'TO'],
            ['name' => 'Nigeria', 'description' => 'ナイジェリア連邦共和国', 'countrycode' => 'NG'],
            ['name' => 'Nauru', 'description' => 'ナウル共和国', 'countrycode' => 'NR'],
            ['name' => 'Namibia', 'description' => 'ナミビア共和国', 'countrycode' => 'NA'],
            ['name' => 'Niue', 'description' => 'ニウエ', 'countrycode' => 'NU'],
            ['name' => 'Nicaragua', 'description' => 'ニカラグア共和国', 'countrycode' => 'NI'],
            ['name' => 'Niger', 'description' => 'ニジェール共和国', 'countrycode' => 'NE'],
            ['name' => 'Japan', 'description' => '日本国', 'countrycode' => 'JP'],
            ['name' => 'New Zealand', 'description' => 'ニュージーランド', 'countrycode' => 'NZ'],
            ['name' => 'Nepal', 'description' => 'ネパール連邦民主共和国', 'countrycode' => 'NP'],
            ['name' => 'Norway', 'description' => 'ノルウェー王国', 'countrycode' => 'NO'],
            ['name' => 'Bahrain', 'description' => 'バーレーン王国', 'countrycode' => 'BH'],
            ['name' => 'Haiti', 'description' => 'ハイチ共和国', 'countrycode' => 'HT'],
            ['name' => 'Pakistan', 'description' => 'パキスタン・イスラム共和国', 'countrycode' => 'PK'],
            ['name' => 'Holy See', 'description' => 'バチカン市国', 'countrycode' => 'VA'],
            ['name' => 'Panama', 'description' => 'パナマ共和国', 'countrycode' => 'PA'],
            ['name' => 'Vanuatu', 'description' => 'バヌアツ共和国', 'countrycode' => 'VU'],
            ['name' => 'Bahamas', 'description' => 'バハマ国', 'countrycode' => 'BS'],
            ['name' => 'Papua New Guinea', 'description' => 'パプアニューギニア独立国', 'countrycode' => 'PG'],
            ['name' => 'Palau', 'description' => 'パラオ共和国', 'countrycode' => 'PW'],
            ['name' => 'Paraguay', 'description' => 'パラグアイ共和国', 'countrycode' => 'PY'],
            ['name' => 'Barbados', 'description' => 'バルバドス', 'countrycode' => 'BB'],
            ['name' => 'Hungary', 'description' => 'ハンガリー', 'countrycode' => 'HU'],
            ['name' => 'Bangladesh', 'description' => 'バングラデシュ人民共和国', 'countrycode' => 'BD'],
            ['name' => 'Timor-Leste', 'description' => '東ティモール民主共和国', 'countrycode' => 'TP'],
            ['name' => 'Fiji', 'description' => 'フィジー共和国', 'countrycode' => 'FJ'],
            ['name' => 'Philippines', 'description' => 'フィリピン共和国', 'countrycode' => 'PH'],
            ['name' => 'Finland', 'description' => 'フィンランド共和国', 'countrycode' => 'FI'],
            ['name' => 'Bhutan', 'description' => 'ブータン王国', 'countrycode' => 'BT'],
            ['name' => 'Brazil', 'description' => 'ブラジル連邦共和国', 'countrycode' => 'BR'],
            ['name' => 'France', 'description' => 'フランス共和国', 'countrycode' => 'FR'],
            ['name' => 'Bulgaria', 'description' => 'ブルガリア共和国', 'countrycode' => 'BG'],
            ['name' => 'Burkina Faso', 'description' => 'ブルキナファソ', 'countrycode' => 'BF'],
            ['name' => 'Brunei Darussalam', 'description' => 'ブルネイ・ダルサラーム国', 'countrycode' => 'BN'],
            ['name' => 'Burundi', 'description' => 'ブルンジ共和国', 'countrycode' => 'BI'],
            ['name' => 'Viet Nam', 'description' => 'ベトナム社会主義共和国', 'countrycode' => 'VN'],
            ['name' => 'Benin', 'description' => 'ベナン共和国', 'countrycode' => 'BJ'],
            ['name' => 'Venezuela', 'description' => 'ベネズエラ・ボリバル共和国', 'countrycode' => 'VE'],
            ['name' => 'Belarus', 'description' => 'ベラルーシ共和国', 'countrycode' => 'BY'],
            ['name' => 'Belize', 'description' => 'ベリーズ', 'countrycode' => 'BZ'],
            ['name' => 'Peru', 'description' => 'ペルー共和国', 'countrycode' => 'PE'],
            ['name' => 'Belgium', 'description' => 'ベルギー王国', 'countrycode' => 'BE'],
            ['name' => 'Poland', 'description' => 'ポーランド共和国', 'countrycode' => 'PL'],
            ['name' => 'Bosnia and Herzegovina', 'description' => 'ボスニア・ヘルツェゴビナ', 'countrycode' => 'BA'],
            ['name' => 'Botswana', 'description' => 'ボツワナ共和国', 'countrycode' => 'BW'],
            ['name' => 'Bolivia', 'description' => 'ボリビア多民族国', 'countrycode' => 'BO'],
            ['name' => 'Portugal', 'description' => 'ポルトガル共和国', 'countrycode' => 'PT'],
            ['name' => 'Honduras', 'description' => 'ホンジュラス共和国', 'countrycode' => 'HN'],
            ['name' => 'Marshall Islands', 'description' => 'マーシャル諸島共和国', 'countrycode' => 'MH'],
            ['name' => 'Madagascar', 'description' => 'マダガスカル共和国', 'countrycode' => 'MG'],
            ['name' => 'Malawi', 'description' => 'マラウイ共和国', 'countrycode' => 'MW'],
            ['name' => 'Mali', 'description' => 'マリ共和国', 'countrycode' => 'ML'],
            ['name' => 'Malta', 'description' => 'マルタ共和国', 'countrycode' => 'MT'],
            ['name' => 'Malaysia', 'description' => 'マレーシア', 'countrycode' => 'MY'],
            ['name' => 'Micronesia (Federated States of)', 'description' => 'ミクロネシア連邦', 'countrycode' => 'FM'],
            ['name' => 'South Africa', 'description' => '南アフリカ共和国', 'countrycode' => 'ZA'],
            ['name' => 'South Sudan', 'description' => '南スーダン共和国', 'countrycode' => 'SS'],
            ['name' => 'Myanmar', 'description' => 'ミャンマー連邦共和国', 'countrycode' => 'MM'],
            ['name' => 'Mexico', 'description' => 'メキシコ合衆国', 'countrycode' => 'MX'],
            ['name' => 'Mauritius', 'description' => 'モーリシャス共和国', 'countrycode' => 'MU'],
            ['name' => 'Mauritania', 'description' => 'モーリタニア・イスラム共和国', 'countrycode' => 'MR'],
            ['name' => 'Mozambique', 'description' => 'モザンビーク共和国', 'countrycode' => 'MZ'],
            ['name' => 'Monaco', 'description' => 'モナコ公国', 'countrycode' => 'MC'],
            ['name' => 'Maldives', 'description' => 'モルディブ共和国', 'countrycode' => 'MV'],
            ['name' => 'Republic of Moldova', 'description' => 'モルドバ共和国', 'countrycode' => 'MD'],
            ['name' => 'Morocco', 'description' => 'モロッコ王国', 'countrycode' => 'MA'],
            ['name' => 'Mongolia', 'description' => 'モンゴル国', 'countrycode' => 'MN'],
            ['name' => 'Montenegro', 'description' => 'モンテネグロ', 'countrycode' => 'ME'],
            ['name' => 'Jordan', 'description' => 'ヨルダン・ハシェミット王国', 'countrycode' => 'JO'],
            ['name' => 'Lao People\'s Democratic Republic', 'description' => 'ラオス人民民主共和国', 'countrycode' => 'LA'],
            ['name' => 'Latvia', 'description' => 'ラトビア共和国', 'countrycode' => 'LV'],
            ['name' => 'Lithuania', 'description' => 'リトアニア共和国', 'countrycode' => 'LT'],
            ['name' => 'Libya', 'description' => 'リビア', 'countrycode' => 'LY'],
            ['name' => 'Liechtenstein', 'description' => 'リヒテンシュタイン公国', 'countrycode' => 'LI'],
            ['name' => 'Liberia', 'description' => 'リベリア共和国', 'countrycode' => 'LR'],
            ['name' => 'Romania', 'description' => 'ルーマニア', 'countrycode' => 'RO'],
            ['name' => 'Luxembourg', 'description' => 'ルクセンブルク大公国', 'countrycode' => 'LU'],
            ['name' => 'Rwanda', 'description' => 'ルワンダ共和国', 'countrycode' => 'RW'],
            ['name' => 'Lesotho', 'description' => 'レソト王国', 'countrycode' => 'LS'],
            ['name' => 'Lebanon', 'description' => 'レバノン共和国', 'countrycode' => 'LB'],
            ['name' => 'Russian Federation', 'description' => 'ロシア連邦', 'countrycode' => 'RU'],
        ];
        $this->nationality->insert($nationalities);
    }
}
